# Generated by Django 3.2.8 on 2021-12-29 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('search_tag', models.CharField(max_length=1000, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('serviceable', models.BooleanField(default=True)),
                ('search_tag', models.CharField(max_length=1000, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=50)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('search_tag', models.CharField(max_length=1000, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm_services.city')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('search_tag', models.CharField(max_length=1000, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm_services.country')),
            ],
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('serviceable', models.DecimalField(decimal_places=0, max_digits=1)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm_services.city')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ranking', models.DecimalField(decimal_places=0, default=1, max_digits=5)),
                ('ranking_source', models.CharField(max_length=120)),
                ('serviceable', models.BooleanField(default=True)),
                ('blacklisted', models.BooleanField(default=False)),
                ('search_tag', models.CharField(max_length=1000, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.CharField(max_length=30)),
                ('updation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updation_by', models.CharField(max_length=30, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm_services.city')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm_services.university')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mdm_services.state'),
        ),
    ]
