# Generated by Django 3.2 on 2022-01-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='search_tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
